### ISSUE TITLE
Logisitical transporter bug!

### ISSUE THREAD

**Issue by ph1823** [mekanism-mod/Mekanism#5060] opened 2018-05-24 20:02 UTC
#### Issue description:
If a can stop the item pass on the conduc, it's dont work. Sorry for my english !

#### Steps to reproduce:
1. Place a Logisitical transporter 
2. Place three chest and connect to the logistrical transporter
3. Stop the connection of one chest
4. Bug is produc, item dont stop

#### Version (make sure you are on the latest version before reporting):
**Forge:**  1.10.2 forge-12.18.3.2511
**Mekanism:** 9.2.4
**Other relevant version:** IDK (or  null?)

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[https://youtu.be/V-2rel3xnOg](YouTube vidéo describe this bug)

**Comment by thiakil** [comment] 2019-03-23 06:12
Duplicate of #4895

**Closed by thiakil** 2019-03-23 06:12 UTC
Labels: Old MC, bug
