### ISSUE TITLE
Thermal Evaporation Base Causing Timeout

### ISSUE THREAD

**Issue by XtraoSnipes** [mekanism-mod/Mekanism#5355] opened 2019-04-07 22:15 UTC
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
I am Playing on my server and the Thermal Evaporation Base is causing me to timeout every time i place one of the blocks and i do not know how to fix this.

#### Steps to reproduce:
1. Place the Thermal Evaporation Base block
2. Done

#### Version (make sure you are on the latest version before reporting):
**Forge 1.12.2 (14.23.5.2824)**
**Mekanism: 1.12.2-9.6.8.366** 
**Other relevant version: 1.12.2** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[gist/pastebin/etc link here]

**Comment by thiakil** [comment] 2019-04-08 00:16
Duplicate of #5354

**Closed by thiakil** 2019-04-08 00:16 UTC
