### ISSUE TITLE
The Curious Case of the Vanishing Digital Miner

### ISSUE THREAD

**Issue by Moobien** [mekanism-mod/Mekanism#4932] opened 2018-02-06 07:40 UTC
#### Issue description:
 Had a Dminer running, went off to get some cobblestone and when returned my Dminer was gone.

#### Steps to reproduce:
1. Start Dminer
2. Go deep underground and do some manual mining
3. Return to Dminer

#### Version (make sure you are on the latest version before reporting):

MekanismGenerators-1.12.2-9.4.3.330
MekanismTools-1.12.2-9.4.3.330
Mekanism-1.12.2-9.4.3.330

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

https://gist.github.com/Moobien/5b0629163fe6094527c7e8554cc3775d

**Comment by Moobien** [comment] 2018-02-06 22:41
It happened twice so far. Both times I had left it running.  I tested it again this morning but put an anchor in it and came back to it still there.

**Comment by Moobien** [comment] 2018-02-07 00:28
Logged out of the game and when I came back the miner had vanished

**Comment by thiakil** [comment] 2018-02-07 00:54
please attempt to reproduce with a minimum set of mods

**Comment by Moobien** [comment] 2018-02-08 08:36
Tested with a fresh install with mek and tinkers only. The miner didnt vanish

**Comment by thiakil** [comment] 2018-02-09 00:27
You will need to begin adding mods back until you can find the culprit(s)

**Comment by ProsperCraft** [comment] 2018-02-13 14:51
Looks like an old bug coming back to haunt - https://github.com/aidancbrady/Mekanism/issues/3718

We are having the same problem on our server as well.

The way to reproduce it is the same way you make this happen- 
https://github.com/aidancbrady/Mekanism/issues/4676

I suspect they are linked.

The last one to go missing was crossing chunk boundaries and did not have a chunk loader upgrade.

Modpack - https://minecraft.curseforge.com/projects/towncraft

**Comment by MarshTheBacca** [comment] 2018-06-17 23:21
I've had this happen 3 times to my digital miners. They're about 40 or 50 chucks away from my base, and i come to check on them to change their configs every now and then depending on my demands, and sometimes i would just see my quantum entangloporter and a few cables sat there but no digital miner to be seen. :? Odd

**Comment by thiakil** [comment] 2018-06-18 02:31
There is not enough info to go in in this issue. It would be advised to not cross chunk borders with the digital miner.

To solve it properly it will need to be reproduced with *just* Mekanism

**Comment by sfxworks** [comment] 2019-01-03 19:37
#### Issue description:

Players placing digital miners have their placement disappear when the chunk unloads.

#### Steps to reproduce:
1. Place the digital miner
2. Star the digital miner
3. Reposition/Disconnect + Unload the chunk

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.23.5.2768
**Mekanism:** 1.12.2-9.4.13.349
**Other relevant version:** 

A player demonstrating this issue:
https://forum.thebobsgamingnetwork.net/t/digital-miner-disappeared/291

**Comment by ProsperCraft** [comment] 2019-01-03 23:35
I just ended up disabling them entirely in my modpack because people were constantly reporting them missing.

**Comment by thiakil** [comment] 2019-01-03 23:37
Are they putting them on chunk borders?

**Comment by qsevers23** [comment] 2019-01-04 00:06
They are, however I have a user that has also had one on a chunk boundary for awhile and nothing has happened to it. However he wasn't using Mekanism's anchor upgrade, he was using chickenchunk's chunk loader block instead

**Comment by ProsperCraft** [comment] 2019-01-04 00:06
The placement does not matter, we tried, crossing chunks, middle of chunk, on the boundry, all the same.

**Comment by qsevers23** [comment] 2019-01-04 00:07
Yeah, I had 3 disappear at the same time. 1 didn't cross any, 1 crossed 1 border, and the last one crossed 2.

**Comment by thiakil** [comment] 2019-01-04 00:09
Is there video evidence of the non-crossing one(s) anywhere?

**Comment by qsevers23** [comment] 2019-01-04 00:16
I don't have any, no

**Comment by thiakil** [comment] 2019-03-21 14:12
This should have been fixed in recent released

**Closed** 2019-03-21 14:12 UTC
