### ISSUE TITLE
hang/Fatal error server disconnect with little tiles mod

### ISSUE THREAD

**Issue by Saereth** [mekanism-mod/Mekanism#5339] opened 2019-04-04 12:58 UTC
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
People are reporting a crash that occurs regularly for them but not at all for other players. I myself experienced this connecting to a server but it eventually went away. This is getting enough attention and causing enough people frustration I wanted to get some reports out to both mod devs that the stacktrace shows in hopes of a fix from either dev. The stacktrace seems to involve both mek and little tiles but im not sure which mod is best suited to the fix so I'm posting to both trackers. 

#### Steps to reproduce:
1. Join a server or switch to LAN game
2. change world
3. error sometimes happens for some people but rarely and hard to reproduce
 
#### Version (make sure you are on the latest version before reporting):
**Forge:** 2795
**Mekanism:** Mekanism-1.12.2-9.6.7.360.jar
**Other relevant version:** LT: LittleTiles_v1.5.0-pre130_mc1.12.2.jar

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

Logifle:
https://cdn.discordapp.com/attachments/563344094043045903/563344186913325094/2019-04-04-6.log

relevant part where the disconnect happens:
`
[23:46:24] [Netty Local Client IO #0/ERROR]: Something went wrong
java.lang.NullPointerException: null
	at mekanism.common.block.BlockBounding.getMainBlockPos(BlockBounding.java:31) ~[BlockBounding.class:?]
	at mekanism.common.block.BlockBounding.getPickBlock(BlockBounding.java:94) [BlockBounding.class:?]
	at li.cil.scannable.util.BlockUtils.getItemStackFromState(BlockUtils.java:23) [BlockUtils.class:?]
	at li.cil.scannable.client.scanning.ScanResultProviderBlock.buildOreCache(ScanResultProviderBlock.java:424) [ScanResultProviderBlock.class:?]
	at li.cil.scannable.client.scanning.ScanResultProviderBlock.rebuildOreCache(ScanResultProviderBlock.java:91) [ScanResultProviderBlock.class:?]
	at li.cil.scannable.common.config.Settings.setServerSettings(Settings.java:272) [Settings.class:?]
	at li.cil.scannable.common.network.Network.onClientDisconnectionFromServer(Network.java:58) [Network.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_3086_Network_onClientDisconnectionFromServer_ClientDisconnectionFromServerEvent.invoke(.dynamic) [?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.close(NetworkDispatcher.java:502) [NetworkDispatcher.class:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeClose(AbstractChannelHandlerContext.java:624) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.access$1100(AbstractChannelHandlerContext.java:38) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext$13.run(AbstractChannelHandlerContext.java:613) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
`

cross posted to little tiles tracker:
https://github.com/CreativeMD/LittleTiles/issues/152

**Comment by thiakil** [comment] 2019-04-05 02:40
duplicate of #5319

**Closed by thiakil** 2019-04-05 02:40 UTC
