### ISSUE TITLE
random crash

### ISSUE THREAD

**Issue by Trixz2018** [mekanism-mod/Mekanism#5402] opened 2019-04-14 23:02 UTC
#### Issue description:
randomly crashing

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.23.5.2835 272
**Mekanism:** 9..7
**Other relevant version:** 

https://paste.dimdev.org/fomiyupewo.mccrash

**Comment by pupnewfster** [comment] 2019-04-14 23:04
Duplicate of #5392 and fixed by #5399

**Closed by pupnewfster** 2019-04-14 23:04 UTC
